print("Cree tonpersonage!")
nom=input("Comment s' appelle ton personnage?")
age=input("Quel age a ton personnage?")
forces=input("Quelles sont les forces de ton personnage?")
faiblesses=input("Quelles sont les faiblesses de ton personnage?")
print("nom:",nom)
print("age:",age)
print("forces:",forces)
print("faiblesses:",faiblesses)
